themes/aura/assets/add-to-cart.js, themes/aura/snippets/add-to-cart.liquid, themes/aura/snippets/single-product-placeholder.liquid, themes/aura/snippets/single-product.liquid, themes/harmony/assets/add-to-cart.js, themes/harmony/snippets/add-to-cart.liquid, themes/harmony/snippets/single-product-placeholder.liquid, themes/harmony/snippets/single-product.liquid, themes/meraki/assets/add-to-cart.js, themes/meraki/snippets/add-to-cart.liquid, themes/meraki/snippets/single-product.liquid
Ticket: [TH-18](https://youcanshop.atlassian.net/browse/TH-18)
- Check this branch locally and run `pnpm run release`
- 3 new files will be generated in this format `theme name + date + .zip`
- Go to [test environment](https://seller-area.testyoucan.shop/admin/themes) seller-area
- Upload each .zip file and activate them and test each one with the following process: 
- In theme editor go to product page > single page section > add to cart block
- Activate skip cart feature
- Now in your storefront theme go to the product page and click on add to cart button
- Check if the page doesn't reload and it takes you to the checkout information page
Please read ticket description for more details
[TH-18]: https://youcanshop.atlassian.net/browse/TH-18?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> TH-18: Order now button doesn't work correctly in new themes

themes/aura/snippets/head-config.liquid, themes/harmony/assets/reviews.css, themes/harmony/snippets/head-config.liquid, themes/meraki/assets/reviews.css, themes/meraki/snippets/head-config.liquid
> [!Note]
> This change doesn't have any significant performance improvement but it is recommended to preconnect resources like fonts to reduce the initial latency involved in DNS lookups
Ticket: [TH-68](https://youcanshop.atlassian.net/browse/TH-68).
[TH-68]: https://youcanshop.atlassian.net/browse/TH-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-68: Preload google font

themes/aura/snippets/product-variants.liquid, themes/harmony/snippets/product-variants.liquid, themes/meraki/snippets/product-variants.liquid
DARK
`<label>` element used with no adjacent or child input element. Practically has no effect.
=> DARK: Remove incorrect use of <label> tag

themes/aura/sections/main-navbar.liquid, themes/aura/sections/notice-bar.liquid, themes/aura/sections/product-reviews.liquid, themes/aura/snippets/head-config.liquid, themes/harmony/sections/main-navbar.liquid, themes/harmony/sections/notice-bar.liquid, themes/harmony/sections/product-reviews.liquid, themes/harmony/snippets/head-config.liquid, themes/meraki/sections/main-navbar.liquid, themes/meraki/sections/notice-bar.liquid, themes/meraki/sections/product-reviews.liquid, themes/meraki/snippets/head-config.liquid
Ticket: [TH-74](https://youcanshop.atlassian.net/browse/TH-74).
- See code 🙂
> [!Important]
> Please read the ticket description.
[TH-74]: https://youcanshop.atlassian.net/browse/TH-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-74: All themes > Performance > Eliminate render-blocking resources

themes/aura/sections/main-navbar.liquid, themes/harmony/sections/main-navbar.liquid, themes/meraki/sections/main-navbar.liquid
Ticket: [TH_70](https://youcanshop.atlassian.net/browse/TH_70).
> [!IMPORTANT]
> If you're installing for the first time, when you check the `navbar` font family, it should have a `default` option selected automatically (the font family of your theme should be the default), instead of being `empty`. In the future, if you update the font family of the navbar and want to `revert` to the original setting, you can simply select the default option to set it back to the `original` font family.
=> TH-70: Theme editor > No way of clearing navbar's font-family

themes/aura/sections/product-column.liquid, themes/aura/snippets/product-home.liquid, themes/harmony/sections/product-column.liquid, themes/harmony/snippets/product-home.liquid, themes/meraki/sections/product-column.liquid, themes/meraki/snippets/product-home.liquid
Ticket: [TH-13](https://youcanshop.atlassian.net/browse/TH-13).
[TH-13]: https://youcanshop.atlassian.net/browse/TH-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-13: All themes > No option to change the CTA button's text in the Product Column section

themes/aura/assets/add-to-cart.js, themes/aura/assets/desktop-slider.css, themes/aura/sections/featured-products.liquid, themes/aura/sections/main-cart.liquid, themes/aura/snippets/quantity-input.liquid, themes/aura/snippets/slider.liquid, themes/harmony/assets/add-to-cart.js, themes/harmony/assets/desktop-slider.css, themes/harmony/sections/featured-products.liquid, themes/harmony/sections/main-cart.liquid, themes/harmony/snippets/quantity-input.liquid, themes/harmony/snippets/slider.liquid, themes/meraki/assets/add-to-cart.js, themes/meraki/assets/desktop-slider.css, themes/meraki/sections/featured-products.liquid, themes/meraki/sections/main-cart.liquid, themes/meraki/snippets/quantity-input.liquid, themes/meraki/snippets/slider.liquid
Ticket: [TH_92](https://youcanshop.atlassian.net/browse/TH_92).
- The title in the feature products section should have an `<h1>` instead of an `<h2>` tag.
- No layout shirt on the slider section after the `height` change. 
- Cart page > `remove item` & `quantity` inputs, now have a `label`.
=> TH-92: All themes > Performance > Audit 1 > Fix the accessibly issues

themes/aura/sections/product.liquid, themes/harmony/sections/product.liquid, themes/meraki/sections/product.liquid
> [!IMPORTANT]
> This PR `restores` some JS code that was accidentally removed. The missing code was `fetching` review data, which caused the product `review` section to disappear. By adding the code back, the section will reappear in the **theme editor** / **stores**. This issue is related to this [ticket](https://github.com/youcan-shop/youcan-themes/pull/18).
```js
document.addEventListener('DOMContentLoaded', () => {
const parentContainer = '.yc-single-product';
fetchReviewsForProduct(sectionProductId, parentContainer, {{ selected_product.averageRating }});
});
```
=> Dark: Restores the JS code that fetches product reviews

themes/meraki/assets/money.js, themes/meraki/assets/product.js, themes/meraki/sections/product.liquid
Ticket: [TH-155](https://youcanshop.atlassian.net/browse/TH-155).
[TH-155]: https://youcanshop.atlassian.net/browse/TH-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-155-meraki: Format product price in product page based on a unified locale code

themes/harmony/assets/money.js, themes/harmony/assets/product.js, themes/harmony/sections/product.liquid
Ticket: [TH-155](https://youcanshop.atlassian.net/browse/TH-155).
[TH-155]: https://youcanshop.atlassian.net/browse/TH-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-155-harmony: Format product price in product page based on a unified locale code

themes/aura/assets/navbar.css, themes/aura/styles/navbar.scss
Ticket: [TH-176](https://youcanshop.atlassian.net/browse/TH-176).
[TH-176]: https://youcanshop.atlassian.net/browse/TH-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-176-aura: Fix logo squished in mobile sidemenu

themes/harmony/assets/navbar.css, themes/harmony/styles/navbar.scss
Ticket: [TH-176](https://youcanshop.atlassian.net/browse/TH-176).
[TH-176]: https://youcanshop.atlassian.net/browse/TH-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-176-harmony: Fix logo squished in mobile cart

themes/aura/assets/add-to-cart.js, themes/aura/assets/main.js, themes/aura/snippets/product-preview.liquid, themes/aura/snippets/product-slider.liquid, themes/aura/snippets/quantity-input.liquid
This fix is also pushed in this [PR](https://github.com/youcan-shop/youcan-themes/pull/65) for harmony theme
=> DARK: aura > fix tracking inventory issue with direct add to cart method

themes/aura/assets/dropdown-menu.js, themes/harmony/assets/add-to-cart.js, themes/harmony/assets/cart.js, themes/harmony/assets/dropdown-menu.js, themes/harmony/assets/express-checkout.css, themes/harmony/assets/express-checkout.js, themes/harmony/assets/main.css, themes/harmony/assets/main.js, themes/harmony/assets/product-quantity-input.js, themes/harmony/assets/product.js, themes/harmony/locales/ar.default.json, themes/harmony/locales/en.json, themes/harmony/locales/fr.json, themes/harmony/snippets/add-to-cart.liquid, themes/harmony/snippets/alert.liquid, themes/harmony/snippets/cart-drawer.liquid, themes/harmony/snippets/product-preview.liquid, themes/harmony/snippets/product-slider.liquid, themes/harmony/snippets/quantity-input.liquid, themes/harmony/styles/express-checkout.scss, themes/harmony/styles/main.scss
Ticket: [TH_109](https://youcanshop.atlassian.net/browse/TH-109)
There are two different scenarios to test this PR:
1- Direct add to cart:
-> On store admin under: Store > theme > Product settings > Advanced > direct add to cart
-> Now theme editor: Theme settings > general settings > direct add to cart
2- Normal mode:
- variant has 0 inventory: express checkout & cart buttons are disabled
- variant has 2 on inventory :  max quantity that the customer can add to cart is 2 if try to add more the popup notification warning show up
- variant has 2 on inventory and 2 on cart:  the popup notification warning show up
**_PS_**: Make sure to test also the cart drawer and the cart page in both scenarios => changing the variant quantity.
=> TH-109: Harmony > Prevent the customer from placing an order if a variant is out of stock

themes/meraki/assets/main.css, themes/meraki/locales/ar.default.json, themes/meraki/locales/en.json, themes/meraki/locales/fr.json, themes/meraki/snippets/alert.liquid, themes/meraki/snippets/cart-drawer.liquid, themes/meraki/styles/main.scss
Ticket: [TH-109](https://youcanshop.atlassian.net/browse/TH-109).
[TH-109]: https://youcanshop.atlassian.net/browse/TH-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-109: Meraki: > Create max inventory popup alert

themes/aura/assets/add-to-cart.js
Ticket: [TH_175](https://youcanshop.atlassian.net/browse/TH_175).
=> TH-175: Aura > Remove repetitive "quantity" label from cart drawer

themes/meraki/assets/add-to-cart.js, themes/meraki/assets/dropdown-menu.js, themes/meraki/assets/express-checkout.css, themes/meraki/assets/express-checkout.js, themes/meraki/assets/main.css, themes/meraki/assets/main.js, themes/meraki/assets/product-quantity-input.js, themes/meraki/assets/product.css, themes/meraki/assets/product.js, themes/meraki/snippets/add-to-cart.liquid, themes/meraki/snippets/express-checkout.liquid, themes/meraki/styles/express-checkout.scss, themes/meraki/styles/main.scss, themes/meraki/styles/product.scss
Ticket: [TH_109](https://youcanshop.atlassian.net/browse/TH_109).
This QA will be focused only on **Product page**
- variant has 0 inventory: express checkout & cart buttons are disabled
- variant has 2 on inventory :  max quantity that the customer can add to cart is 2 if try to add more the popup notification warning show up
- variant has 2 on inventory and 2 on cart:  the popup notification warning show up
I have also fix some CSS issues on Express checkout form
=> TH-109: Meraki > Product page > Prevent the customer from placing an order if a variant is out of stock

themes/meraki/assets/add-to-cart.js, themes/meraki/assets/cart.js, themes/meraki/snippets/product-preview.liquid, themes/meraki/snippets/product-slider.liquid, themes/meraki/snippets/quantity-input.liquid
Ticket: [TH_109](https://youcanshop.atlassian.net/browse/TH_109).
-> On store admin under: Store > theme > Product settings > Advanced > direct add to cart
-> Now theme editor: Theme settings > general settings > direct add to cart
=> TH-109 > Meraki > Cart page & (direct add to cart) > Prevent the customer from placing an order if a variant is out of stock

themes/aura/assets/express-checkout.css, themes/aura/snippets/express-checkout.liquid, themes/aura/snippets/single-product-placeholder.liquid, themes/aura/styles/express-checkout.scss, themes/harmony/assets/express-checkout.css, themes/harmony/snippets/express-checkout.liquid, themes/harmony/snippets/single-product-placeholder.liquid, themes/harmony/styles/express-checkout.scss, themes/meraki/snippets/single-product-placeholder.liquid
=> DARK : Fix express checkout block CSS

themes/harmony/sections/product.liquid, themes/harmony/snippets/add-to-cart.liquid, themes/harmony/snippets/product-preview.liquid, themes/harmony/snippets/product-slider.liquid, themes/harmony/snippets/single-product-placeholder.liquid, themes/harmony/snippets/single-product.liquid
Ticket: [TH_187](https://youcanshop.atlassian.net/browse/TH_187).
=> TH-187: Harmony > Refactoring skip cart feature

themes/aura/assets/express-checkout.js, themes/harmony/assets/express-checkout.js, themes/meraki/assets/express-checkout.js
Ticket: [TH_186](https://youcanshop.atlassian.net/browse/TH_186).
- Please make sure to upload theme on you Prod account in seller area and do not use dev mode because it will not gonna work.
- I have also faced this issue (we got the backend content mixed with some HTML) I did a temporary fix until we find out how to solve it.
=> TH-186 New themes > Express checkout > Max checkout amount error is missing

themes/harmony/assets/cart.css, themes/harmony/assets/cart.js, themes/harmony/assets/main.js, themes/harmony/locales/ar.default.json, themes/harmony/locales/en.json, themes/harmony/locales/fr.json, themes/harmony/sections/main-cart.liquid, themes/harmony/snippets/cart-drawer.liquid, themes/harmony/snippets/quantity-input.liquid, themes/harmony/styles/cart.scss
Ticket: [TH-174](https://youcanshop.atlassian.net/browse/TH-174).
> [!Note]
> Note that if your IP address while using VPN is in UK, and you have Arabic as the browser language, then you might see a flash where the price is displayed in indic numerals at first then Arabic numbers `١٢٣.٩٩ ' -> `123.99`. This is likely an issue with how PHP handles ar-GB vs how javaScript handles it. Will tackle this issue in a separate PR.
[TH-174]: https://youcanshop.atlassian.net/browse/TH-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-174: Harmony > Cart Page > Format product price by the Dotshop object's locale code

themes/origins/assets/component-slider.css, themes/origins/assets/main.css, themes/origins/assets/product-card.css, themes/origins/assets/products-by-collection.css, themes/origins/config/settings_schema.json, themes/origins/locales/ar.json, themes/origins/locales/en.default.json, themes/origins/locales/fr.json, themes/origins/sections/default.liquid, themes/origins/sections/products-by-collection.liquid, themes/origins/sections/slideshow.liquid, themes/origins/snippets/product-card.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/base/_reset.scss, themes/origins/styles/component-slider.scss, themes/origins/styles/product-card.scss, themes/origins/styles/products-by-collection.scss, themes/origins/templates/index.json
Ticket: [TH-230](https://youcanshop.atlassian.net/browse/TH-230).
- Collection
- Title (Section)
- Description (Section)
- Header position: Left, Right, Center
- View Style: Grid, or Slides
- Text Color
- Background color
- Maximum products to show
- Number of columns on desktop
- Show link to collection
- Enable quick add (This setting won’t work since we don’t have neither the cart or the modal logic yet)
- Section Spacing (Top, bottom)
> [!Note]
>
> You might find some responsitivity issues when the section is in "Slides" mode. That's an issue with our core slider and will be fixed in the PR of this [ticket](https://youcanshop.atlassian.net/browse/TH-285). 
> Another issue arose where the contents of the slides are not responsive to user clicks …
=> TH-230: Add Products-by-Collection section

.prettierrc, themes/origins/sections/search.liquid, themes/origins/sections/single-collection.liquid, themes/origins/snippets/yc-pagination.liquid
Dark
> [!IMPORTANT]
> I've also increased prettier's printWidth to 100, that's because wrapping liquid `assign` tags cause them to not work
> for example:
> This would not work
>	```
>	{% 
>    assign page_params = page_params 
>      | append: 'q=' 
>      | append: terms 
>      | append: '&' 
>    %}
> ```
> But this will
> ```
> {% assign page_params = page_params | append: 'q=' | append: terms | append: '&' %}
> ```
=> DARK: Origins > Fix pagination and sort url construction 

themes/origins/sections/thank-you.liquid, themes/origins/templates/index.json
=> Dark: Fix thank you page total

themes/aura/assets/navbar.css, themes/aura/styles/navbar.scss, themes/harmony/assets/navbar.css, themes/harmony/styles/navbar.scss, themes/meraki/assets/navbar.css, themes/meraki/styles/navbar.scss
Ticket: [TH-351](https://youcanshop.atlassian.net/browse/TH-351).
[TH-351]: https://youcanshop.atlassian.net/browse/TH-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-351: All themes > store logo is stretched when visiting from a mobile device

themes/origins/snippets/head-config.liquid
| Before | After |
| <img width="300" alt="Screenshot 2025-03-07 at 10 45 38" src="https://github.com/user-attachments/assets/7442b5bf-1391-444a-a884-8a7ad75cc3f3" /> | <img width="300" alt="Screenshot 2025-03-07 at 10 45 25" src="https://github.com/user-attachments/assets/e9687abc-9c84-4350-9dca-4503bf7adf2a" /> | 
=> Dark: Origins > Set background  color for default favicon svg

themes/origins/assets/product-card.css, themes/origins/snippets/product-description.liquid, themes/origins/styles/product-card.scss
=> DARK: Origins > Fix page width break on mobile

themes/origins/sections/featured-product.liquid, themes/origins/sections/single-product.liquid
Ticket: [TH-408](https://youcanshop.atlassian.net/browse/TH-408).
[TH-408]: https://youcanshop.atlassian.net/browse/TH-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-408: Origins > Countown timer minute and second not calc'ed

themes/origins/assets/cart.js, themes/origins/assets/component-product-form.js, themes/origins/locales/ar.json, themes/origins/locales/en.default.json, themes/origins/locales/fr.json, themes/origins/snippets/product-add-to-cart.liquid, themes/origins/snippets/product-buy-button.liquid, themes/origins/snippets/product-card.liquid, themes/origins/snippets/product-quick-view.liquid, themes/origins/snippets/yc-add-to-cart.liquid, themes/origins/snippets/yc-express-checkout.liquid
Ticket: [TH-413](https://youcanshop.atlassian.net/browse/TH-413).
> [!NOTE]
> Ensure your store's checkout type is set to "Normal"
](https://seller-area.youcan.shop/admin/theme#product)
| Disabled | Enabled |
| <img width="150" alt="Screenshot 2025-03-24 at 13 04 02" src="https://github.com/user-attachments/assets/d977b5e4-9943-43b4-9ff2-95da4a4f309d" /> | <img width="150" alt="Screenshot 2025-03-24 at 13 03 29" src="https://github.com/user-attachments/assets/0fd767dc-e284-4710-9b5b-050298451f46" /> | 
> [!NOTE]
> Make sure the [global](https://seller-area.youcan.shop/admin/theme#product) "Skip cart" feature is turned off
> Verify that the change affects only the product you’ve chosen
[TH-413]: …
=> TH-413: Origins > Product Card > Show "Shop now" if skip cart is enabled

themes/origins/assets/component-upsell.js, themes/origins/sections/upsell.liquid
Ticket: [TH-377](https://youcanshop.atlassian.net/browse/TH-377).
[TH-377]: https://youcanshop.atlassian.net/browse/TH-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-377: Origins > Upsell pages don't stack up when there are more than one upsell with different weights
