youcan-shop/youcan-themes

themes/aura/snippets/slider.liquid, themes/harmony/snippets/slider.liquid, themes/meraki/snippets/slider.liquid
[TH-38](https://youcanshop.atlassian.net/browse/TH-38)
Leave empty when you have nothing to say
[TH-38]: https://youcanshop.atlassian.net/browse/TH-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-38: New Themes > Homepage > Prevent largest content paint from being lazy loaded

themes/aura/sections/featured-product-slider.liquid, themes/aura/sections/related-products.liquid, themes/harmony/sections/featured-product-slider.liquid, themes/harmony/sections/related-products.liquid, themes/meraki/sections/featured-product-slider.liquid, themes/meraki/sections/related-products.liquid
[TH-49](https://youcanshop.atlassian.net/browse/TH-49)
-  [ ] Go to product slider section and remove all blocks and test if the problem is solved 
FYI read ticket description
[TH-49]: https://youcanshop.atlassian.net/browse/TH-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-49 : Theme pages become unresponsive and freeze when the seller attempts to customize his store for all themes

.github/pull_request_template.md, themes/aura/assets/product.js, themes/aura/snippets/product-variants.liquid, themes/harmony/assets/product.js, themes/harmony/snippets/product-variants.liquid, themes/meraki/assets/product.js, themes/meraki/snippets/product-variants.liquid
[TH-17](https://youcanshop.atlassian.net/browse/TH-17)
FYI read ticket description
[TH-17]: https://youcanshop.atlassian.net/browse/TH-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-17 : Variants Price doesn't update in new themes

.gitignore
DARK
Leave empty when you have nothing to say
=> DARK: ignore `dist/` folder

themes/aura/assets/desktop-slider.css, themes/aura/assets/mobile-slider.css, themes/aura/sections/desktop-slider.liquid, themes/aura/snippets/slider.liquid, themes/aura/styles/desktop-slider.scss, themes/aura/styles/mobile-slider.scss, themes/harmony/assets/desktop-slider.css, themes/harmony/sections/desktop-slider.liquid, themes/harmony/snippets/slider.liquid, themes/harmony/styles/desktop-slider.scss, themes/harmony/styles/mobile-slider.scss, themes/meraki/assets/desktop-slider.css, themes/meraki/sections/desktop-slider.liquid, themes/meraki/snippets/slider.liquid, themes/meraki/styles/desktop-slider.scss, themes/meraki/styles/mobile-slider.scss
[TH-9](https://youcanshop.atlassian.net/browse/TH-9)
Please read the ticket description.
[TH-9]: https://youcanshop.atlassian.net/browse/TH-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-9: Themes > Slider Image button colors can’t be changed

.github/pull_request_template.md
=> DARK: Improve PR template

themes/aura/assets/reviews-count.js, themes/aura/assets/reviews.js, themes/aura/sections/main-navbar.liquid, themes/aura/sections/main-search.liquid, themes/aura/snippets/cart-drawer.liquid, themes/aura/snippets/related-products-slider.liquid, themes/meraki/snippets/product-quantity-input.liquid
[TH-57](https://youcanshop.atlassian.net/browse/TH-57)
[TH-57]: https://youcanshop.atlassian.net/browse/TH-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-57: Aura > Product page > Fix and add missing accessibility attributes

themes/harmony/assets/reviews-count.js, themes/harmony/assets/reviews.js, themes/harmony/sections/main-footer.liquid, themes/harmony/sections/main-navbar.liquid, themes/harmony/sections/main-search.liquid, themes/harmony/sections/related-products.liquid, themes/harmony/snippets/cart-drawer.liquid, themes/harmony/snippets/product-quantity-input.liquid, themes/harmony/snippets/related-products-slider.liquid
[TH-58](https://youcanshop.atlassian.net/browse/TH-58)
[TH-58]: https://youcanshop.atlassian.net/browse/TH-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-58: Harmony > Product page > Fix and add missing accessibility attributes

themes/aura/sections/related-products.liquid
=> DARK: Fix related product slider perPage

.gitignore, themes/aura/assets/navbar.css, themes/aura/sections/main-navbar.liquid, themes/harmony/assets/navbar.css, themes/harmony/sections/main-navbar.liquid, themes/meraki/assets/navbar.css, themes/meraki/sections/main-navbar.liquid, themes/meraki/styles/navbar.scss
[TH-6](https://youcanshop.atlassian.net/browse/TH-6)
-  [ ]  Test the new menu customization options
Leave empty when you have nothing to say
[TH-6]: https://youcanshop.atlassian.net/browse/TH-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-6: Theme Editor > Mobile burger menu color is not configurable

themes/aura/assets/reviews-count.js, themes/aura/assets/reviews.css, themes/aura/assets/reviews.js, themes/aura/locales/en.json, themes/aura/sections/product-reviews.liquid, themes/aura/sections/product.liquid, themes/aura/snippets/reviews.liquid, themes/aura/styles/reviews.scss, themes/harmony/assets/reviews.css, themes/harmony/assets/reviews.js, themes/harmony/locales/en.json, themes/harmony/sections/product-reviews.liquid, themes/harmony/sections/product.liquid, themes/harmony/snippets/reviews.liquid, themes/harmony/styles/reviews.scss, themes/meraki/assets/reviews-count.js, themes/meraki/assets/reviews.css, themes/meraki/assets/reviews.js, themes/meraki/locales/en.json, themes/meraki/sections/product-reviews.liquid, themes/meraki/sections/product.liquid, themes/meraki/snippets/product-home.liquid, themes/meraki/snippets/reviews.liquid, themes/meraki/styles/reviews.scss
Ticket: [TH-11](https://youcanshop.atlassian.net/browse/TH-11).
[TH-11]: https://youcanshop.atlassian.net/browse/TH-11?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-11: Themes > Can’t modify/hide "add comment button" in product review

themes/aura/assets/cart.js, themes/aura/assets/main.js, themes/aura/snippets/slider.liquid, themes/aura/styles/main.scss, themes/harmony/assets/cart.js, themes/harmony/assets/main.js, themes/harmony/snippets/slider.liquid, themes/harmony/styles/main.scss, themes/meraki/assets/cart.js, themes/meraki/assets/main.js, themes/meraki/sections/main-navbar.liquid, themes/meraki/snippets/slider.liquid, themes/meraki/styles/main.scss
Ticket: [TH-73](https://youcanshop.atlassian.net/browse/TH-73).
> [!IMPORTANT]  
> Got some time?  Check it on `Google Chrome` & `Safari` to ensure we’re all set.
[TH-73]: https://youcanshop.atlassian.net/browse/TH-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-73: All themes > Performance > Avoid large layout shifts

themes/aura/assets/product.js, themes/harmony/assets/product.js, themes/meraki/assets/product.js
Ticket: [TH-71](https://youcanshop.atlassian.net/browse/TH-71).
https://github.com/user-attachments/assets/0cd10277-8289-4683-b986-afc2b2d85a29
[TH-71]: https://youcanshop.atlassian.net/browse/TH-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-71: Product Page > Fix Dropdown not applying default value

themes/aura/assets/product.js, themes/aura/snippets/product-images-showcase.liquid, themes/harmony/assets/product.js, themes/harmony/snippets/product-images-showcase.liquid, themes/meraki/assets/product.js, themes/meraki/snippets/product-images-showcase.liquid
Ticket: [TH-80](https://youcanshop.atlassian.net/browse/TH-80).
* Title: `حذاء  لورو بيانا`
* Description: `حذاء موكاسين رياضي مصنوع من الجلد السويدي الناعم والمريح للغاية. النعل مصنوع من المطاط، وهي ميزة تميز جميع أحذية لورو بيانا الرياضية. الحذاء مزين بشريط صغير في الأمام مع دلايات "My Charms" المصغرة. يعد اختيارًا مثاليًا للصيف، سواء كنت ستقضين يومك على الشاطئ، في زيارة العائلة، أو في الخروج مع الأصدقاء.`
* Price: `250`
* Images
* Bleu Ciel
* Marron
* Beige
* Vert
[TH-80]: https://youcanshop.atlassian.net/browse/TH-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-80: Product Page > Variants Images not showing when clicked (Mobile)

themes/aura/assets/product-slider.css, themes/aura/sections/featured-product-slider.liquid, themes/aura/styles/product-slider.scss, themes/harmony/assets/product-slider.css, themes/harmony/sections/featured-product-slider.liquid, themes/harmony/styles/product-slider.scss, themes/meraki/assets/product-slider.css, themes/meraki/sections/featured-product-slider.liquid, themes/meraki/styles/product-slider.scss
Ticket: [TH_12](https://youcanshop.atlassian.net/browse/TH_12).
=> TH-12: COD Themes > Product slider isn't displaying properly when page is missing Slider section

themes/aura/assets/desktop-slider.css, themes/aura/styles/desktop-slider.scss, themes/harmony/assets/desktop-slider.css, themes/harmony/styles/desktop-slider.scss, themes/meraki/assets/desktop-slider.css, themes/meraki/styles/desktop-slider.scss
=> Dark: TH-92 > Add missing Scss code

themes/aura/assets/navbar.css, themes/aura/sections/main-navbar.liquid, themes/aura/styles/navbar.scss, themes/harmony/assets/navbar.css, themes/harmony/sections/main-footer.liquid, themes/harmony/sections/main-navbar.liquid, themes/harmony/styles/navbar.scss, themes/meraki/assets/navbar.css, themes/meraki/sections/main-footer.liquid, themes/meraki/sections/main-navbar.liquid, themes/meraki/styles/navbar.scss
Ticket: [TH_101](https://youcanshop.atlassian.net/browse/TH_101).
**`BEFORE`**
**`AFTER`**
> [!IMPORTANT]
> You can apply the same QA on the footer section
=> TH-101: All themes > Fix logo dimensions > Incorrect height rendering for seller customization

themes/harmony/assets/reviews-count.js
Ticket: [TH_106](https://youcanshop.atlassian.net/browse/TH_106).
**`Preview`**
=> TH-106: Harmony > "Add your comment" button doesn't show in product page

themes/aura/assets/desktop-slider.css, themes/aura/assets/mobile-slider.css, themes/aura/sections/desktop-slider.liquid, themes/aura/snippets/slider.liquid, themes/aura/styles/desktop-slider.scss, themes/aura/styles/mobile-slider.scss, themes/harmony/assets/desktop-slider.css, themes/harmony/assets/mobile-slider.css, themes/harmony/sections/desktop-slider.liquid, themes/harmony/snippets/slider.liquid, themes/harmony/styles/desktop-slider.scss, themes/harmony/styles/mobile-slider.scss, themes/meraki/assets/desktop-slider.css, themes/meraki/assets/mobile-slider.css, themes/meraki/sections/desktop-slider.liquid, themes/meraki/snippets/slider.liquid, themes/meraki/styles/desktop-slider.scss, themes/meraki/styles/mobile-slider.scss
Ticket: [TH_107](https://youcanshop.atlassian.net/browse/TH_107).
**`Preview`**
=> TH-107: All new themes > Slider Content and button can’t change position

themes/aura/assets/reviews.js, themes/harmony/assets/reviews.js, themes/meraki/assets/reviews.js
Ticket: [TH-110](https://youcanshop.atlassian.net/browse/TH-110).
[TH-110]: https://youcanshop.atlassian.net/browse/TH-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-110: Reviews > Dates are not formatted when fetched with Show more

themes/aura/sections/featured-product-slider.liquid, themes/harmony/sections/featured-product-slider.liquid, themes/meraki/sections/featured-product-slider.liquid
Ticket: [TH_117](https://youcanshop.atlassian.net/browse/TH_117).
> [!NOTE]
> _Desktop_ -> `default` : 3 | `max` : 10 | `min`: 1
> _Mobile_ -> `default` : 2 | `max` : 4 | `min`: 1
**`Preview`**
=> TH-117: All themes > Product slider > There's no option to set the number of products per slide

themes/aura/assets/desktop-slider.css, themes/aura/assets/main.css, themes/aura/assets/mobile-slider.css, themes/aura/sections/main-page.liquid, themes/aura/snippets/breadcrumbs.liquid, themes/aura/styles/desktop-slider.scss, themes/aura/styles/main.scss, themes/harmony/assets/desktop-slider.css, themes/harmony/assets/main.css, themes/harmony/assets/mobile-slider.css, themes/harmony/assets/navbar.css, themes/harmony/snippets/breadcrumbs.liquid, themes/harmony/styles/desktop-slider.scss, themes/harmony/styles/main.scss, themes/harmony/styles/mobile-slider.scss, themes/meraki/assets/main.css, themes/meraki/assets/mobile-slider.css, themes/meraki/config/settings_schema.json, themes/meraki/sections/main-page.liquid, themes/meraki/snippets/breadcrumbs.liquid, themes/meraki/styles/desktop-slider.scss, themes/meraki/styles/main.scss, themes/meraki/styles/mobile-slider.scss
**I have also pushed some auto generated CSS files because I noticed that sometimes we don't push them or we made some changes directly on them and we forget to make those changes on SCSS files**
=> Dark - fixing the direction of the arrows

themes/aura/locales/ar.default.json, themes/aura/locales/en.json, themes/aura/locales/fr.json, themes/aura/sections/main-cart.liquid
Ticket: [TH_149](https://youcanshop.atlassian.net/browse/TH_149)
=> TH-149: Aura theme > Modify the row header through Cart Page

themes/aura/sections/product.liquid, themes/aura/snippets/add-to-cart.liquid, themes/aura/snippets/product-preview.liquid, themes/aura/snippets/product-slider.liquid, themes/aura/snippets/single-product-placeholder.liquid, themes/aura/snippets/single-product.liquid
Ticket: [TH_187](https://youcanshop.atlassian.net/browse/TH_187).
=> TH-187: Aura > Refactoring skip cart feature

themes/meraki/sections/product.liquid, themes/meraki/snippets/add-to-cart.liquid, themes/meraki/snippets/product-preview.liquid, themes/meraki/snippets/product-slider.liquid, themes/meraki/snippets/single-product-placeholder.liquid, themes/meraki/snippets/single-product.liquid
Ticket: [TH_ 187](https://youcanshop.atlassian.net/browse/TH_ 187).
=> TH-187: Meraki > Refactoring skip cart feature 

themes/aura/assets/express-checkout.js, themes/harmony/assets/express-checkout.js, themes/meraki/assets/express-checkout.js
=> DARK: reverting changes of 4.2.5 release in express-checkout.js

themes/meraki/sections/featured-product-slider.liquid, themes/meraki/sections/related-products.liquid, themes/meraki/snippets/product-slider.liquid, themes/meraki/snippets/related-products-slider.liquid
Ticket: [TH-211](https://youcanshop.atlassian.net/browse/TH-211).
[TH-211]: https://youcanshop.atlassian.net/browse/TH-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-211: Meraki > Fix product & featured products sliders direction not same as document direction

themes/aura/sections/featured-product-slider.liquid, themes/aura/sections/related-products.liquid, themes/aura/snippets/product-slider.liquid, themes/aura/snippets/related-products-slider.liquid
Ticket: [TH-211](https://youcanshop.atlassian.net/browse/TH-211).
[TH-211]: https://youcanshop.atlassian.net/browse/TH-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-211: Aura > Fix product & featured products sliders direction not same as document direction

themes/harmony/sections/featured-product-slider.liquid, themes/harmony/sections/related-products.liquid, themes/harmony/snippets/product-slider.liquid, themes/harmony/snippets/related-products-slider.liquid
Ticket: [TH-211](https://youcanshop.atlassian.net/browse/TH-211).
[TH-211]: https://youcanshop.atlassian.net/browse/TH-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-211: Harmony > Fix product & featured products sliders direction not same as document direction

themes/aura/sections/related-products.liquid, themes/harmony/sections/related-products.liquid, themes/meraki/sections/related-products.liquid
Ticket: [TH-214](https://youcanshop.atlassian.net/browse/TH-214).
> [!Note]
>
> Repeat these steps for Aura, Harmony, and Meraki
|  Before  |  After  |
|---------------------------------|---------------------------------|
|         <img width="1178" alt="Screenshot 2024-11-07 at 3 29 42 PM" src="https://github.com/user-attachments/assets/17f49a66-97d2-4582-ab01-69aad337b1f3">          |         <img width="1164" alt="Screenshot 2024-11-07 at 3 29 53 PM" src="https://github.com/user-attachments/assets/5b9a9b9b-0cbb-4dc1-8265-f98266a74a6e">           |
|  Before  |  After  |
|---------------------------------|---------------------------------|
|      <img width="1200" alt="Screenshot 2024-11-07 at 3 26 44 PM" src="https://github.com/user-attachments/assets/edd850fb-4956-47a9-94a2-38473459a14 …
=> TH-214: All themes > Fix related products slider perPage

themes/aura/assets/cart.css, themes/aura/assets/featured-products.css, themes/aura/assets/main.css, themes/aura/assets/navbar.css, themes/aura/assets/product-listing.css, themes/aura/assets/product.css, themes/aura/assets/thankyou.css, themes/aura/postcss.config.js
DARK
To make sure that no breaks happen after this change, the best course of action is to visually check each component that was affected by this change, these components are:
- cart
- featured products
- main
- navbar
- product-listing
- product
- thankyou
Let's QA each of these
- Summary box item price
- table header & row cells
- Section title
- Dropdown button
- Close drawer button
- product images splide list and thumbnail
- table rows and total
=> DARK: Aura > Disable logical properties postCSS plugin feature

themes/harmony/assets/cart.css, themes/harmony/assets/featured-products.css, themes/harmony/assets/main.css, themes/harmony/assets/navbar.css, themes/harmony/assets/product-column.css, themes/harmony/assets/product-listing.css, themes/harmony/assets/product.css, themes/harmony/postcss.config.js
DARK
To make sure that no breaks happen after this change, the best course of action is to visually check each component that was affected by this change, these components are:
- cart
- featured products
- main
- navbar
- product-column
- product-listing
- product
- thankyou
Let's QA each of these
- Summary box item price and table
- mobile > table product details
- Section title
- Dropdown button
- Product description
- Close drawer button
- product images splide list and thumbnail
=> DARK: Harmony > Disable logical properties postCSS plugin feature

themes/meraki/assets/footer.css, themes/meraki/assets/main.css, themes/meraki/assets/product.css, themes/meraki/assets/reviews.css, themes/meraki/postcss.config.js
DARK
To make sure that no breaks happen after this change, the best course of action is to visually check each component that was affected by this change, these components are:
- footer
- main
- product
- reviews
Let's QA each of these
- Menu item
- Dropdown button
- thumbnail and slider images
- review items
=> DARK: Meraki > Disable logical properties postCSS plugin feature

themes/aura/sections/product.liquid, themes/aura/snippets/countdown.liquid, themes/aura/snippets/product-placeholder.liquid, themes/aura/snippets/product-preview.liquid, themes/aura/snippets/single-product-placeholder.liquid, themes/aura/snippets/single-product.liquid
Ticket: [TH-210](https://youcanshop.atlassian.net/browse/TH-210).
For product slider:
- in home page remove all default sections 
- add product slider section only
For countdown block in single product section:
- in home page remove all default sections
- add single product section
- add countdown block
[TH-210]: https://youcanshop.atlassian.net/browse/TH-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-210: Aura > Missing Countdown CSS in (product slider section & countdown block in single product section)

themes/aura/assets/cart.js, themes/harmony/assets/cart.js, themes/meraki/assets/cart.css, themes/meraki/assets/cart.js, themes/meraki/sections/main-cart.liquid, themes/meraki/styles/cart.scss
Ticket: [TH-183](https://youcanshop.atlassian.net/browse/TH-183).
I have also fixed some CSS + content in Meraki theme related to the summary box of the cart page
[TH-183]: https://youcanshop.atlassian.net/browse/TH-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-183: Coupons with discount type of fixed are displayed as percentage 

.vscode/extensions.json, .vscode/settings.json
Dark
Presuming you're using VSCode:
=> DARK: .vscode/settings.json > Add liquid and json formatting + recommnded extensions

themes/origins/sections/default.liquid, themes/origins/snippets/yc-icon.liquid
Ticket: [TH-239](https://youcanshop.atlassian.net/browse/TH-239).
[TH-239]: https://youcanshop.atlassian.net/browse/TH-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-239-option-1: Add yc-icon liquid snippet

themes/origins/assets/layout-header.css, themes/origins/assets/layout-header.js, themes/origins/postcss.config.js, themes/origins/sections/header.liquid, themes/origins/snippets/yc-icon.liquid, themes/origins/styles/layout-header.scss
Ticket: [TH-247](https://youcanshop.atlassian.net/browse/TH-247).
[TH-247]: https://youcanshop.atlassian.net/browse/TH-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-247: Origins > Layout > Header > Handle the search bar

themes/origins/assets/component-drawer.css, themes/origins/assets/component-drawer.js, themes/origins/assets/header-menu-drawer.css, themes/origins/assets/layout-header.css, themes/origins/assets/main.css, themes/origins/sections/header.liquid, themes/origins/snippets/head-config.liquid, themes/origins/snippets/header-cart-drawer.liquid, themes/origins/snippets/header-menu-drawer.liquid, themes/origins/snippets/yc-icon.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/base/_reset.scss, themes/origins/styles/component-drawer.scss, themes/origins/styles/header-menu-drawer.scss, themes/origins/styles/layout-header.scss
Ticket: [TH-255](https://youcanshop.atlassian.net/browse/TH-255).
> [!IMPORTANT]  
> make sure to read the ticket description + audit the page with [Lighthouse](https://developer.chrome.com/docs/lighthouse)
[TH-255]: https://youcanshop.atlassian.net/browse/TH-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-255: Origins > Layout > Header > Handle the side menu

themes/origins/assets/component-drawer.css, themes/origins/assets/main.css, themes/origins/sections/default.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/component-drawer.scss
Ticket: [TH-238](https://youcanshop.atlassian.net/browse/TH-238).
> [!IMPORTANT]  
> Please read the ticket description.
```liquid
<section
class="section-core"
style="--space-top: 100px; --space-bottom: 100px;"
>
<div class="section-head" data-position="center">
<h1 class="title">Your title</h1>
<p class="description">Your description</p>
</div>
<div class="section-content">...</div>
</section>
```
[TH-238]: https://youcanshop.atlassian.net/browse/TH-238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-238: Origins > Create yc-section core component

themes/aura/assets/add-to-cart.js, themes/aura/assets/cart.js, themes/aura/assets/main.js, themes/aura/assets/product.js, themes/aura/snippets/cart-drawer.liquid, themes/aura/snippets/product-preview.liquid, themes/aura/snippets/product-slider.liquid, themes/aura/snippets/quantity-input.liquid
Ticket: [TH-252](https://youcanshop.atlassian.net/browse/TH-252).
- In store-admin activate the tracking inventory in:
- In theme editor:
- In store-front check the inventory tracking in:
[TH-252]: https://youcanshop.atlassian.net/browse/TH-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-252: Aura > Refactoring the variant inventory check in the front end

themes/harmony/assets/add-to-cart.js, themes/harmony/assets/cart.js, themes/harmony/assets/main.js, themes/harmony/assets/product.js, themes/harmony/snippets/cart-drawer.liquid, themes/harmony/snippets/product-preview.liquid, themes/harmony/snippets/product-slider.liquid, themes/harmony/snippets/quantity-input.liquid
Ticket: [TH-252](https://youcanshop.atlassian.net/browse/TH-252).
- In store-admin activate the tracking inventory in:
- In theme editor:
- In store-front check the inventory tracking in:
[TH-252]: https://youcanshop.atlassian.net/browse/TH-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-252: Harmony > Refactoring the variant inventory check in the front end

themes/meraki/assets/add-to-cart.js, themes/meraki/assets/cart.js, themes/meraki/assets/main.js, themes/meraki/assets/product.js, themes/meraki/snippets/cart-drawer.liquid, themes/meraki/snippets/product-preview.liquid, themes/meraki/snippets/product-slider.liquid, themes/meraki/snippets/quantity-input.liquid
Ticket: [TH-252](https://youcanshop.atlassian.net/browse/TH-252).
- In store-admin activate the tracking inventory in:
- In theme editor:
- In store-front check the inventory tracking in:
[TH-252]: https://youcanshop.atlassian.net/browse/TH-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-252: Meraki > Refactoring the variant inventory check in the front end 

themes/origins/sections/footer.liquid
=> DARK: Origins > Hide social links container if no links provided

themes/meraki/assets/cart.css, themes/meraki/assets/cart.js, themes/meraki/assets/main.js, themes/meraki/locales/en.json, themes/meraki/sections/main-cart.liquid, themes/meraki/snippets/quantity-input.liquid, themes/meraki/styles/cart.scss
Ticket: [TH-174](https://youcanshop.atlassian.net/browse/TH-174).
> [!Note]
> Note that if your IP address while using VPN is in UK, and you have Arabic as the browser language, then you might see a flash where the price is displayed in indic numerals at first then Arabic numbers `١٢٣.٩٩ ' -> `123.99`. This is likely an issue with how PHP handles ar-GB vs how javaScript handles it. Will tackle this issue in a separate PR.
[TH-174]: https://youcanshop.atlassian.net/browse/TH-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-174: Meraki > Cart Page > Format product price by the Dotshop object's locale code #64

themes/origins/assets/announcement-bar.css, themes/origins/assets/main.css, themes/origins/config/settings_data.json, themes/origins/layouts/theme.liquid, themes/origins/sections/announcement-bar.liquid, themes/origins/snippets/head-config.liquid, themes/origins/styles/announcement-bar.scss, themes/origins/styles/base/_common.scss, themes/origins/styles/base/_reset.scss
Ticket: [TH-228](https://youcanshop.atlassian.net/browse/TH-228).
[TH-228]: https://youcanshop.atlassian.net/browse/TH-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-228: Add announcement bar section

themes/aura/assets/main.css, themes/aura/assets/main.js, themes/aura/snippets/alert.liquid, themes/aura/styles/main.scss
Ticket: [TH-250](https://youcanshop.atlassian.net/browse/TH-250).
[TH-250]: https://youcanshop.atlassian.net/browse/TH-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-250: Aura > Flash of unstyled toast 

themes/harmony/assets/main.css, themes/harmony/assets/main.js, themes/harmony/snippets/alert.liquid, themes/harmony/styles/main.scss
Ticket: [TH-250](https://youcanshop.atlassian.net/browse/TH-250).
[TH-250]: https://youcanshop.atlassian.net/browse/TH-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-250: Harmony > Flash of unstyled toast 

themes/meraki/assets/main.css, themes/meraki/assets/main.js, themes/meraki/snippets/alert.liquid, themes/meraki/styles/main.scss
Ticket: [TH-250](https://youcanshop.atlassian.net/browse/TH-250).
[TH-250]: https://youcanshop.atlassian.net/browse/TH-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-250: Meraki > Flash of unstyled toast

themes/origins/assets/component-drawer.css, themes/origins/assets/header-menu-drawer.css, themes/origins/assets/layout-header.css, themes/origins/assets/main.css, themes/origins/config/settings_schema.json, themes/origins/sections/default.liquid, themes/origins/sections/header.liquid, themes/origins/snippets/head-config.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/base/_global.scss, themes/origins/styles/base/_reset.scss, themes/origins/styles/component-drawer.scss, themes/origins/styles/header-menu-drawer.scss, themes/origins/styles/layout-header.scss
Ticket: [TH-279](https://youcanshop.atlassian.net/browse/TH-279).
I've also made some changes to the header, but since it's still mainly static and the customization settings aren't linked I just made some changes to the code. We'll address the header customization in this [ticket](https://youcanshop.atlassian.net/browse/TH-280).
[TH-279]: https://youcanshop.atlassian.net/browse/TH-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-279: Origins > Add global button colors to global settings

themes/aura/assets/cart.css, themes/aura/locales/ar.default.json, themes/aura/locales/en.json, themes/aura/locales/fr.json, themes/aura/sections/main-cart.liquid, themes/aura/styles/cart.scss
Ticket: [TH-265](https://youcanshop.atlassian.net/browse/TH-265).
[TH-265]: https://youcanshop.atlassian.net/browse/TH-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-265: Aura > Removing the available shipping options from the summary box of the cart page

themes/harmony/assets/cart.css, themes/harmony/locales/ar.default.json, themes/harmony/locales/en.json, themes/harmony/locales/fr.json, themes/harmony/sections/main-cart.liquid, themes/harmony/styles/cart.scss
Ticket: [TH-265](https://youcanshop.atlassian.net/browse/TH-265).
[TH-265]: https://youcanshop.atlassian.net/browse/TH-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-265: Harmony > Removing the available shipping options from the summary box of the cart page

themes/meraki/assets/cart.css, themes/meraki/locales/ar.default.json, themes/meraki/locales/en.json, themes/meraki/locales/fr.json, themes/meraki/sections/main-cart.liquid, themes/meraki/styles/cart.scss
Ticket: [TH-265](https://youcanshop.atlassian.net/browse/TH-265).
[TH-265]: https://youcanshop.atlassian.net/browse/TH-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-265: Meraki > Removing the available shipping options from the summary box of the cart page

themes/origins/assets/component-drawer.css, themes/origins/assets/header-cart-drawer.css, themes/origins/assets/header-menu-drawer.css, themes/origins/assets/layout-footer.css, themes/origins/assets/layout-header.css, themes/origins/assets/main.css, themes/origins/layouts/theme.liquid, themes/origins/sections/footer.liquid, themes/origins/sections/header.liquid, themes/origins/snippets/header-cart-drawer.liquid, themes/origins/snippets/header-menu-drawer.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/base/_global.scss, themes/origins/styles/base/_reset.scss, themes/origins/styles/component-drawer.scss, themes/origins/styles/header-cart-drawer.scss, themes/origins/styles/header-menu-drawer.scss, themes/origins/styles/layout-footer.scss, themes/origins/styles/layout-header.scss
Ticket: [TH_280](https://youcanshop.atlassian.net/browse/TH_280).
> [!IMPORTANT]
> Made some adjustments to our common styles (button, input) to improve flexibility for customization. The ticket description explains the reasoning & changes.
HEADER
| Option | Type | Status
|--------|--------|--------|
| Sticky mode | boolean | ✅ |
| Bottom border | boolean | ✅ |
| Text color | color | ✅ |
| Bg color | color | ✅ |
| ~Bottom border color~ | ~color~ | 🚫 |
| ~height~ | ~number (px)~ | 🚫 |
=> TH-280: Origins > Header > Make header settings + menu dynamic

themes/aura/assets/add-to-cart.js, themes/aura/assets/cart.css, themes/aura/snippets/product-quantity-input.liquid, themes/aura/styles/cart.scss
Ticket: [TH-267](https://youcanshop.atlassian.net/browse/TH-267).
[TH-267]: https://youcanshop.atlassian.net/browse/TH-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-267: Aura > Flip the quantity input controls so that plus is on the right and minus is on the leftnput direction

themes/harmony/assets/add-to-cart.js, themes/harmony/assets/cart.css, themes/harmony/snippets/product-quantity-input.liquid, themes/harmony/styles/cart.scss
Ticket: [TH-267](https://youcanshop.atlassian.net/browse/TH-267).
[TH-267]: https://youcanshop.atlassian.net/browse/TH-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-267: Harmony > Flip the quantity input controls so that plus is on the right and minus is on the leftnput direction

themes/aura/sections/desktop-slider.liquid, themes/aura/sections/featured-collections.liquid, themes/aura/sections/multi-column.liquid, themes/harmony/sections/desktop-slider.liquid, themes/harmony/sections/featured-collections.liquid, themes/harmony/sections/multi-column.liquid, themes/meraki/sections/desktop-slider.liquid, themes/meraki/sections/featured-collections.liquid, themes/meraki/sections/multi-column.liquid
Ticket: [TH-281](https://youcanshop.atlassian.net/browse/TH-281).
1. Slider
2. multi-column
3. featured collections
[TH-281]: https://youcanshop.atlassian.net/browse/TH-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-281: New themes > Some sections display incorrect block count (-/50)

themes/meraki/assets/cart.css, themes/meraki/snippets/product-quantity-input.liquid, themes/meraki/styles/cart.scss
Ticket: [TH-267](https://youcanshop.atlassian.net/browse/TH-267).
[TH-267]: https://youcanshop.atlassian.net/browse/TH-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-267: Meraki > Flip the quantity input controls so that plus is on the right and minus is on the leftnput direction

themes/origins/assets/main.css, themes/origins/sections/featured-product.liquid, themes/origins/styles/base/_common.scss, themes/origins/templates/index.json
Ticket: [TH-232](https://youcanshop.atlassian.net/browse/TH-232).
- Product (select)
- Space top and bottom (range)
> [!NOTE]
>  This PR only introduces the single product section, subsequent PRs will introduce its blocks (See linked issues: https://youcanshop.atlassian.net/browse/TH-232)
[TH-232]: https://youcanshop.atlassian.net/browse/TH-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-232: Origins > Add single product section

themes/origins/assets/main.css, themes/origins/config/settings_schema.json, themes/origins/sections/featured-product.liquid, themes/origins/snippets/accordion.liquid, themes/origins/snippets/yc-icon.liquid, themes/origins/styles/base/_common.scss
Ticket: [TH-298](https://youcanshop.atlassian.net/browse/TH-298).
[TH-298]: https://youcanshop.atlassian.net/browse/TH-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-298: Origins > Add accordion block

themes/aura/assets/thankyou.css, themes/aura/sections/thankyou.liquid, themes/aura/styles/thankyou.scss, themes/harmony/assets/thankyou.css, themes/harmony/sections/thankyou.liquid, themes/harmony/styles/thankyou.scss, themes/meraki/assets/thankyou.css, themes/meraki/sections/thankyou.liquid, themes/meraki/styles/thankyou.scss
Ticket: [TH-244](https://youcanshop.atlassian.net/browse/TH-244).
related to this [PR](https://github.com/youcan-shop/youcanmono/pull/9209)
[TH-244]: https://youcanshop.atlassian.net/browse/TH-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DARK: related to (TH-244) >  New themes > fix the display of the coupon value on thankyou page

themes/origins/assets/component-product-media.js, themes/origins/assets/component-slider.css, themes/origins/assets/main.css, themes/origins/sections/featured-product.liquid, themes/origins/sections/products.liquid, themes/origins/snippets/head-config.liquid, themes/origins/snippets/yc-icon.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/component-slider.scss
Ticket: [TH-299](https://youcanshop.atlassian.net/browse/TH-299).
[TH-299]: https://youcanshop.atlassian.net/browse/TH-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-299: Origins > Single Product > Add media section

themes/aura/assets/cart-drawer.css, themes/aura/assets/main.js, themes/aura/assets/navbar.css, themes/aura/styles/cart-drawer.scss, themes/aura/styles/navbar.scss, themes/harmony/assets/main.js, themes/harmony/assets/navbar.css, themes/harmony/sections/main-navbar.liquid, themes/harmony/styles/navbar.scss
Ticket: [TH-304](https://youcanshop.atlassian.net/browse/TH-304).
For Aura & Harmony theme only
[TH-304]: https://youcanshop.atlassian.net/browse/TH-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-304: New Themes > Menu drawer enters from the same position regardless whether the page is RTL or LTR

themes/origins/assets/cart.css, themes/origins/assets/main.css, themes/origins/sections/default.liquid, themes/origins/sections/multi-column.liquid, themes/origins/snippets/breadcrumb.liquid, themes/origins/snippets/yc-icon.liquid, themes/origins/styles/base/_common.scss
Ticket: [TH-320](https://youcanshop.atlassian.net/browse/TH-320).
[TH-320]: https://youcanshop.atlassian.net/browse/TH-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-320: Origins > Add breadcrumb snippet

themes/origins/assets/component-modal.css, themes/origins/assets/component-modal.js, themes/origins/assets/component-select.css, themes/origins/assets/featured-product.css, themes/origins/assets/main.css, themes/origins/locales/ar.json, themes/origins/locales/en.default.json, themes/origins/locales/fr.json, themes/origins/sections/default.liquid, themes/origins/sections/featured-product.liquid, themes/origins/snippets/product-buy-button.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/component-modal.scss, themes/origins/styles/component-select.scss, themes/origins/styles/featured-product.scss
Ticket: [TH-297](https://youcanshop.atlassian.net/browse/TH-297).
> [!IMPORTANT]
> Please read the ticket description.
| Desktop | Mobile |
| <img width="250" alt="Screenshot 2025-01-24 at 12 04 34" src="https://github.com/user-attachments/assets/43122e50-ad75-468c-8299-e83915b3aa27" /> | <img width="125" alt="Screenshot 2025-01-24 at 12 09 11" src="https://github.com/user-attachments/assets/fe1ac536-9c01-4242-8fab-2f89adcd99f4" />
[TH-297]: https://youcanshop.atlassian.net/browse/TH-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-297: Origins > Single Product Section > Create Buy buttons block

themes/origins/sections/all-collections.liquid
Ticket: [TH-312](https://youcanshop.atlassian.net/browse/TH-312).
| | Type | default |
|--------|--------|--------|
| Text color | :color | `#121212FF` |
| Bg color | :color | `#FFFFFFFF` |
| Nbr columns | :number | `3` |
| Space top | :number | `50` (px) |
| Space bottom | :number | `50` (px) | 
| Default | Empty |
| <img width="300" alt="Screenshot 2025-01-28 at 11 58 15" src="https://github.com/user-attachments/assets/6c90dea0-7af0-44b9-8bda-03d810310699" /> | <img width="300" alt="Screenshot 2025-01-28 at 11 58 44" src="https://github.com/user-attachments/assets/36b22c03-3cfc-49d9-adf2-80375847edda" /> | 
[TH-312]: https://youcanshop.atlassian.net/browse/TH-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> TH-312: Origins > Create collections page

themes/origins/assets/main.css, themes/origins/assets/product-listing.css, themes/origins/locales/ar.json, themes/origins/locales/en.default.json, themes/origins/locales/fr.json, themes/origins/sections/header.liquid, themes/origins/sections/search.liquid, themes/origins/sections/single-collection.liquid, themes/origins/snippets/yc-icon.liquid, themes/origins/snippets/yc-pagination.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/product-listing.scss
Ticket: [TH-342](https://youcanshop.atlassian.net/browse/TH-342).
[TH-342]: https://youcanshop.atlassian.net/browse/TH-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-342: Origins > Add pagination snippet

themes/origins/assets/component-modal.js, themes/origins/assets/featured-product.css, themes/origins/sections/product-reviews.liquid, themes/origins/snippets/product-buy-button.liquid, themes/origins/styles/featured-product.scss
=> Dark: Origins > Implement the new syntax logic of the 'yc-modal'

themes/origins/assets/featured-product.css, themes/origins/assets/main.css, themes/origins/assets/product-reviews.css, themes/origins/config/settings_schema.json, themes/origins/sections/product-reviews.liquid, themes/origins/sections/single-product.liquid, themes/origins/styles/featured-product.scss, themes/origins/styles/product-reviews.scss, themes/origins/templates/product.json
Ticket: [TH-311](https://youcanshop.atlassian.net/browse/TH-311).
> [!NOTE]
> Note that the product reviews section is static for now, it will be handled in another PR.
[TH-311]: https://youcanshop.atlassian.net/browse/TH-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-311: Origins > Add single product page

themes/origins/assets/component-cart-drawer-items.js, themes/origins/assets/component-product-form.js, themes/origins/assets/component-quantity-control.js, themes/origins/assets/main.css, themes/origins/locales/ar.json, themes/origins/locales/en.default.json, themes/origins/locales/fr.json, themes/origins/snippets/cart-drawer-item.liquid, themes/origins/snippets/head-config.liquid, themes/origins/snippets/yc-quantity-control.liquid, themes/origins/styles/base/_common.scss
Ticket: [TH-328](https://youcanshop.atlassian.net/browse/TH-328).
> [!Note]
> We'll cover QA Steps for two use cases: Inventory tracking **ON**, and **OFF**
https://github.com/user-attachments/assets/2c59f8f9-ec27-4269-b427-fe92c2a89c65
https://github.com/user-attachments/assets/74897124-010b-4e70-94e5-4c804b2f5ad1
[TH-328]: https://youcanshop.atlassian.net/browse/TH-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-328: Origins > Add ability to change cart item quantity

themes/origins/assets/component-modal.css, themes/origins/assets/component-modal.js, themes/origins/assets/component-variants.css, themes/origins/assets/product-card.css, themes/origins/assets/product-quick-view.css, themes/origins/sections/default.liquid, themes/origins/snippets/product-card.liquid, themes/origins/snippets/product-quick-view.liquid, themes/origins/snippets/variant-toggle.liquid, themes/origins/styles/component-modal.scss, themes/origins/styles/component-variants.scss, themes/origins/styles/product-card.scss, themes/origins/styles/product-quick-view.scss
Ticket: [TH_307](https://youcanshop.atlassian.net/browse/TH_307).
| Desktop | Mobile |
| <img width="200" alt="Screenshot 2025-02-06 at 10 36 02" src="https://github.com/user-attachments/assets/81b86ed7-8926-4c2e-8879-2087d06a15ae" /> | <img width="100" alt="Screenshot 2025-02-06 at 10 36 21" src="https://github.com/user-attachments/assets/ed8821cb-f77d-4c7f-897c-e91494e7510f" /> |
=> TH-307: Origins > Add product variant selector modal

themes/origins/assets/component-cart-drawer-items.js, themes/origins/assets/main.css, themes/origins/snippets/cart-drawer-item.liquid, themes/origins/styles/base/_common.scss
Ticket: [TH-329](https://youcanshop.atlassian.net/browse/TH-329).
https://github.com/user-attachments/assets/ea945d08-d1e9-4a91-aacf-a64ddba50364
[TH-329]: https://youcanshop.atlassian.net/browse/TH-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-329: Origins > Add remove item from cart drawer functionality

themes/origins/locales/ar.json, themes/origins/locales/en.default.json, themes/origins/locales/fr.json, themes/origins/snippets/product-add-to-cart.liquid, themes/origins/snippets/product-card.liquid, themes/origins/snippets/product-quick-view.liquid, themes/origins/snippets/yc-buy-button.liquid
Ticket: [TH-352](https://youcanshop.atlassian.net/browse/TH-352).
```liquid
{% comment %} product-card.liquid {% endcomment %} 
{% render 'yc-buy-button', variants: product.variants %}
``` 
[TH-352]: https://youcanshop.atlassian.net/browse/TH-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-352: Origins > Product card > Handle "buy button" snippet

themes/origins/assets/layout-header.css, themes/origins/sections/header.liquid, themes/origins/styles/layout-header.scss
Ticket: [TH-353](https://youcanshop.atlassian.net/browse/TH-353).
- Desktop logo position
- Mobile logo position
[TH-353]: https://youcanshop.atlassian.net/browse/TH-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-353: Origins > Header > Allow seller to change logo position

themes/origins/assets/review-modal.css, themes/origins/sections/multi-column.liquid, themes/origins/snippets/review-modal.liquid, themes/origins/snippets/yc-icon.liquid, themes/origins/styles/review-modal.scss
Ticket: [TH-310](https://youcanshop.atlassian.net/browse/TH-310).
> [!IMPORTANT]
> This PR covers only the UI.
> Translation will come in another [ticket](https://youcanshop.atlassian.net/browse/TH-331?atlOrigin=eyJpIjoiYWM3MTQ5NzI0MTYwNDUwYjgzMjU3YmVjNTJlZjIzODgiLCJwIjoiaiJ9).
| Dektop | Mobile | -- |
|--------|--------|--------|
| <img width="200" alt="Screenshot 2025-02-17 at 12 22 55" src="https://github.com/user-attachments/assets/ba67f638-80d1-4176-a45e-1bcf7d40d706" /> | <img width="100" alt="Screenshot 2025-02-17 at 12 23 10" src="https://github.com/user-attachments/assets/eb062aab-2eaf-4733-a3ae-12aa26d5037b" /> | <img width="200" alt="Screenshot 2025-02-17 at 12 52 42" src="https://github.com/user-attachments/assets/42a4ebf5-3b63-4449-89bb-d2650d4d6ed4" /> | 
Leave empty when …
=> TH-310: Origins > Product page > Add reviews modal

themes/origins/assets/cart.css, themes/origins/assets/header-cart-drawer.css, themes/origins/snippets/cart-drawer-item.liquid, themes/origins/snippets/cart-item.liquid, themes/origins/styles/cart.scss, themes/origins/styles/header-cart-drawer.scss
Ticket: [TH-359](https://youcanshop.atlassian.net/browse/TH-359).
[TH-359]: https://youcanshop.atlassian.net/browse/TH-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-359: Origins > Cart > Fix cart list UI issues

themes/origins/assets/header-menu-drawer.css, themes/origins/assets/layout-footer.css, themes/origins/assets/layout-header.css, themes/origins/styles/header-menu-drawer.scss, themes/origins/styles/layout-footer.scss, themes/origins/styles/layout-header.scss
- the colors of the search bar are now dynamic
- you can see the menu links in full width (on mobile)
- social media links have been aligned with the store's logo
=> DARK: Layout > Fix some UI issues

themes/origins/assets/component-modal.js, themes/origins/assets/component-toast.css, themes/origins/assets/component-write-review.js, themes/origins/assets/main.css, themes/origins/assets/review-modal.css, themes/origins/assets/write-review.css, themes/origins/locales/ar.json, themes/origins/locales/en.default.json, themes/origins/locales/fr.json, themes/origins/sections/default.liquid, themes/origins/sections/multi-column.liquid, themes/origins/sections/product-reviews.liquid, themes/origins/snippets/head-config.liquid, themes/origins/snippets/write-review.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/component-toast.scss, themes/origins/styles/write-review.scss
Ticket: [TH-309](https://youcanshop.atlassian.net/browse/TH-309).
| Action | Desktop | Mobile |
|--------|--------|--------|
| <img width="200" alt="Screenshot 2025-02-24 at 09 38 47" src="https://github.com/user-attachments/assets/8bf81ca6-7ee3-4e0c-8cd1-a1ba6c4a0655" /> | <img width="200" alt="Screenshot 2025-02-24 at 09 39 05" src="https://github.com/user-attachments/assets/58fa3710-aa79-43a8-8423-699c04cbdde7" /> | <img width="100" alt="Screenshot 2025-02-24 at 09 39 31" src="https://github.com/user-attachments/assets/7a59b842-b378-4357-a7ff-bf3ec7de2983" /> | 
[TH-309]: https://youcanshop.atlassian.net/browse/TH-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-309: Origins > As a buyer I want to be able to write a review

themes/origins/assets/page.css, themes/origins/sections/page.liquid, themes/origins/styles/page.scss, themes/origins/templates/page.json
Ticket: [TH-366](https://youcanshop.atlassian.net/browse/TH-366).
[TH-366]: https://youcanshop.atlassian.net/browse/TH-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-366: Origins > Add custom page template

themes/aura/assets/reviews.js, themes/harmony/assets/reviews.js, themes/meraki/assets/reviews.js
Ticket: [TH-357](https://youcanshop.atlassian.net/browse/TH-357).
[TH-357]: https://youcanshop.atlassian.net/browse/TH-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-357: New themes > Prevent the 'show more' button from disabling if more reviews are available 

themes/origins/assets/component-select.css, themes/origins/snippets/yc-sort.liquid, themes/origins/styles/component-select.scss
=> Dark: Origins > Enable outside click to close yc-sort

themes/origins/layouts/theme.liquid
Ticket: [TH-380](https://youcanshop.atlassian.net/browse/TH-380).
[TH-380]: https://youcanshop.atlassian.net/browse/TH-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-380: Origins > Adapt theme lang and dir to store lang

themes/origins/config/settings_schema.json, themes/origins/snippets/head-config.liquid
Ticket: [TH-379](https://youcanshop.atlassian.net/browse/TH-379).
[TH-379]: https://youcanshop.atlassian.net/browse/TH-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-379: Origins > Add option to change font

themes/origins/assets/component-product.js, themes/origins/assets/featured-product.css, themes/origins/sections/featured-product.liquid, themes/origins/sections/single-product.liquid, themes/origins/snippets/head-config.liquid, themes/origins/snippets/product-inventory-status.liquid, themes/origins/styles/featured-product.scss
=> Dark: Origins > Keep inventory status in sync with variation changes

themes/origins/snippets/head-config.liquid
Ticket: [TH-382](https://youcanshop.atlassian.net/browse/TH-382).
[TH-382]: https://youcanshop.atlassian.net/browse/TH-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-382: Origins > Add Body Font Scaling

themes/origins/assets/header-menu-drawer.css, themes/origins/assets/layout-footer.css, themes/origins/assets/layout-header.css, themes/origins/sections/footer.liquid, themes/origins/sections/header.liquid, themes/origins/snippets/header-menu-drawer.liquid, themes/origins/styles/header-menu-drawer.scss, themes/origins/styles/layout-footer.scss, themes/origins/styles/layout-header.scss
| Tall image | Wide image |
| ![pexels-photo-1400249](https://github.com/user-attachments/assets/9d159cc6-256e-4e97-b5f2-cdf0157cdd8f) | ![sephora-logo-black](https://github.com/user-attachments/assets/d2d4de27-36df-491c-9dab-a79b54b96740) |
=> DARK: Origins > Make header & footer logo width customizable

themes/origins/assets/multi-column.css, themes/origins/sections/footer.liquid, themes/origins/sections/multi-column.liquid, themes/origins/styles/multi-column.scss
=> DARK: Origins > Add multi-column num of columns option

themes/origins/assets/product-card.css, themes/origins/styles/product-card.scss
=> DARK: Origins > fix: remove unsupported css property value

themes/origins/assets/cart.css, themes/origins/snippets/cart-item.liquid, themes/origins/styles/cart.scss
=> DARK: Origins > fix: remove link from cart item title

themes/origins/sections/header.liquid, themes/origins/sections/multi-column.liquid, themes/origins/sections/page.liquid, themes/origins/sections/products-by-collection.liquid, themes/origins/sections/products.liquid, themes/origins/sections/related-products.liquid
Ticket: [TH-399](https://youcanshop.atlassian.net/browse/TH-399).
[TH-399]: https://youcanshop.atlassian.net/browse/TH-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-399: Origins > Resolve bugs related to schema settings

themes/origins/assets/cart.css, themes/origins/assets/header-cart-drawer.css, themes/origins/assets/main.css, themes/origins/sections/cart.liquid, themes/origins/snippets/cart-drawer-item.liquid, themes/origins/snippets/cart-item.liquid, themes/origins/snippets/header-cart-drawer.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/cart.scss, themes/origins/styles/header-cart-drawer.scss
Ticket: [TH-403](https://youcanshop.atlassian.net/browse/TH-403).
[TH-403]: https://youcanshop.atlassian.net/browse/TH-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-403: Origins > Resolve issues related to cart drawer

themes/origins/assets/component-reviews.js, themes/origins/assets/component-testimonials.js, themes/origins/assets/global.js, themes/origins/assets/testimonial-card.css, themes/origins/sections/product-testimonials.liquid, themes/origins/styles/testimonial-card.scss
Ticket: [TH-400](https://youcanshop.atlassian.net/browse/TH-400).
[TH-400]: https://youcanshop.atlassian.net/browse/TH-400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-400: Origins > Resolve bugs related to testimonials / reviews

themes/origins/assets/layout-header.css, themes/origins/assets/layout-header.js, themes/origins/sections/header.liquid, themes/origins/styles/layout-header.scss
Ticket: [TH-398](https://youcanshop.atlassian.net/browse/TH-398).
[TH-398]: https://youcanshop.atlassian.net/browse/TH-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-398: Origins > Resolve bugs related to theme layout

themes/origins/assets/featured-product.css, themes/origins/assets/header-cart-drawer.css, themes/origins/assets/main.css, themes/origins/assets/page.css, themes/origins/assets/product-card.css, themes/origins/assets/product-quick-view.css, themes/origins/assets/write-review.css, themes/origins/config/settings_schema.json, themes/origins/snippets/head-config.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/featured-product.scss, themes/origins/styles/header-cart-drawer.scss, themes/origins/styles/page.scss, themes/origins/styles/product-card.scss, themes/origins/styles/product-quick-view.scss, themes/origins/styles/write-review.scss
Ticket: [TH-416](https://youcanshop.atlassian.net/browse/TH-416).
| Area | Screenshot |
| Cart page | <img width="1652" alt="SCR-20250320-liuq" src="https://github.com/user-attachments/assets/40676fac-0d8a-4910-839e-0c0042b03f1a" /> | 
| Cart drawer | <img width="1726" alt="SCR-20250320-lixp" src="https://github.com/user-attachments/assets/606e0130-a7c0-4511-88e4-52e147171e0d" /> |
| Contact Form | <img width="1706" alt="SCR-20250320-ljcw" src="https://github.com/user-attachments/assets/6a5127f4-a813-4c00-8b4c-e2307ccf85b4" /> |
| Reviews Modal | <img width="1715" alt="SCR-20250320-ljiu" src="https://github.com/user-attachments/assets/703b32ce-72b6-48dd-a073-e7609e11095f" /> |
| Add to cart | <img width="1715" alt="SCR-20250320-ljmn" …
=> TH-416: Origins > Fix global button and typography settings

themes/aura/assets/upsell.js, themes/aura/sections/main-upsell.liquid, themes/harmony/assets/upsell.js, themes/harmony/sections/main-upsell.liquid, themes/meraki/assets/upsell.js, themes/meraki/sections/main-upsell.liquid
Ticket: 
Please read the investigation result that is mentioned in the ticket description.
[TH-377]: https://youcanshop.atlassian.net/browse/TH-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-377: All themes > Upsell pages don't stack up when there are more than one upsell with different weights

themes/origins/assets/component-product-form.js, themes/origins/assets/component-product-media.js, themes/origins/assets/component-product.js, themes/origins/assets/component-slider.css, themes/origins/assets/component-upload.js, themes/origins/assets/component-variants.css, themes/origins/assets/featured-product.css, themes/origins/assets/main.css, themes/origins/sections/featured-product.liquid, themes/origins/sections/single-product.liquid, themes/origins/snippets/product-buy-button.liquid, themes/origins/snippets/product-card.liquid, themes/origins/snippets/product-quick-view.liquid, themes/origins/snippets/product-variants.liquid, themes/origins/snippets/yc-add-to-cart.liquid, themes/origins/snippets/yc-express-checkout.liquid, themes/origins/styles/base/_common.scss, themes/origins/styles/component-slider.scss, themes/origins/styles/component-variants.scss, themes/origins/styles/featured-product.scss
Ticket: [TH-402](https://youcanshop.atlassian.net/browse/TH-402).
[TH-402]: https://youcanshop.atlassian.net/browse/TH-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-402: Origins > Resolve bugs related to featured product

themes/origins/assets/layout-header.css, themes/origins/styles/layout-header.scss
Ticket: [TH_406](https://youcanshop.atlassian.net/browse/TH_406).
=> TH-406: Origins > Add close animation to search bar

themes/origins/sections/related-products.liquid
Ticket: [TH-412](https://youcanshop.atlassian.net/browse/TH-412).
[TH-412]: https://youcanshop.atlassian.net/browse/TH-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-412: Origins > chore: add hint to related products section

themes/origins/sections/all-collections.liquid
Ticket: [TH-415](https://youcanshop.atlassian.net/browse/TH-415).
[TH-415]: https://youcanshop.atlassian.net/browse/TH-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-415: Origins > chore: increase limit of collections shown

themes/origins/assets/component-slider.css, themes/origins/assets/component-slider.js, themes/origins/styles/component-slider.scss
Ticket: [TH-401](https://youcanshop.atlassian.net/browse/TH-401).
[TH-401]: https://youcanshop.atlassian.net/browse/TH-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-401-v2: Refactor yc-modal movement logic

themes/origins/snippets/meta-tags.liquid
Ticket: [TH-420](https://youcanshop.atlassian.net/browse/TH-420).
> [!NOTE]
> In the seller area, you might've noticed there's a custom meta images there. It wasn't taken into consideration since the urls are relatively saved (without the CDN domain) so if we applied them in our theme we'd end up with:
> ```html
> <meta property="og:image"content="/stores/52a53607402bdd1dcc16c6624056ab2c/products/OmF7Td1gM9wJcRvfMe2o543hG0tu6ZrxMcYQSPoC_md.jpg">
> ```
> When it should be like this:
> ```html
> <meta property="og:image"content="https://cdn.youcan.shop//stores/52a53607402bdd1dcc16c6624056ab2c/products/OmF7Td1gM9wJcRvfMe2o543hG0tu6ZrxMcYQSPoC_md.jpg">
> ```
[TH-420]: https://youcanshop.atlassian.net/browse/TH-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> TH-420: Origins > og title and description adapt to product page

themes/origins/assets/component-write-review.js, themes/origins/assets/product-reviews.css, themes/origins/styles/product-reviews.scss
Ticket: [TH-411](https://youcanshop.atlassian.net/browse/TH-411).
| Before | After |
| <img width="1725" alt="image" src="https://github.com/user-attachments/assets/31097b0f-4116-48eb-a8eb-55878c394abf" /> | <img width="1728" alt="image" src="https://github.com/user-attachments/assets/71b68014-8d67-4c64-a61d-638d0b749c33" /> | 
[TH-411]: https://youcanshop.atlassian.net/browse/TH-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-411: Origins > Fix long review text breaks grid

themes/aura/layouts/theme.liquid, themes/aura/snippets/head-config.liquid, themes/aura/snippets/meta-tags.liquid, themes/aura/snippets/page-title.liquid
Ticket: [TH-394](https://youcanshop.atlassian.net/browse/TH-394).
[TH-394]: https://youcanshop.atlassian.net/browse/TH-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-394: Aura > Fix and add missing meta tags

themes/harmony/layouts/theme.liquid, themes/harmony/snippets/head-config.liquid, themes/harmony/snippets/meta-tags.liquid, themes/harmony/snippets/page-title.liquid
Ticket: [TH-394](https://youcanshop.atlassian.net/browse/TH-394).
[TH-394]: https://youcanshop.atlassian.net/browse/TH-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-394: Harmony > Fix and add missing meta tags

themes/meraki/layouts/theme.liquid, themes/meraki/snippets/head-config.liquid, themes/meraki/snippets/meta-tags.liquid, themes/meraki/snippets/page-title.liquid
Ticket: [TH-394](https://youcanshop.atlassian.net/browse/TH-394).
[TH-394]: https://youcanshop.atlassian.net/browse/TH-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-394: Meraki > Fix and add missing meta tags 

themes/origins/assets/product-reviews.css, themes/origins/locales/ar.json, themes/origins/sections/product-reviews.liquid, themes/origins/styles/product-reviews.scss
Ticket: [TH-419](https://youcanshop.atlassian.net/browse/TH-419).
[TH-419]: https://youcanshop.atlassian.net/browse/TH-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-419: Origins > Add option to show/hide 'write review' button

themes/origins/assets/product-reviews.css, themes/origins/assets/testimonial-card.css, themes/origins/styles/product-reviews.scss, themes/origins/styles/testimonial-card.scss
Ticket: [TH-411](https://youcanshop.atlassian.net/browse/TH-411).
| Before | After |
| <img width="1728" alt="SCR-20250326-mpng" src="https://github.com/user-attachments/assets/828b79a0-2fb1-4ff0-a449-bb8167d227fe" /> | <img width="1728" alt="SCR-20250326-mppx" src="https://github.com/user-attachments/assets/b5b65c41-715b-4c85-a659-1aff8035a4be" /> | 
[TH-411]: https://youcanshop.atlassian.net/browse/TH-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-411: Origins > fix long text breaks testimonials section

themes/origins/config/settings_schema.json, themes/origins/sections/thank-you.liquid
=> DARK: Origins > Theme editor schema > fix general settings content

themes/origins/assets/upsell.css, themes/origins/styles/upsell.scss
=> DARK: Origins > Safari browser > fix upsell page UI on mobile screen

themes/aura/layouts/theme.liquid, themes/harmony/layouts/theme.liquid, themes/meraki/layouts/theme.liquid
Ticket: [TH-448](https://youcanshop.atlassian.net/browse/TH-448).
[TH-448]: https://youcanshop.atlassian.net/browse/TH-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-448: Add canonical url to page head

themes/aura/assets/thankyou.css, themes/aura/styles/thankyou.scss, themes/harmony/assets/thankyou.css, themes/harmony/styles/thankyou.scss
Ticket: [TH-446](https://youcanshop.atlassian.net/browse/TH-446).
> [!NOTE]
> Affected themes: `Aura` & `Harmony`
[TH-446]: https://youcanshop.atlassian.net/browse/TH-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-446: New Themes > Thank you page > Wide images are squished

themes/aura/snippets/head-config.liquid, themes/harmony/snippets/head-config.liquid, themes/meraki/snippets/head-config.liquid
Ticket: [TH-456](https://youcanshop.atlassian.net/browse/TH-456).
For each of the themes, make sure you do the following in your QA:
[TH-456]: https://youcanshop.atlassian.net/browse/TH-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TH-456: Fix ionicons icons not showing
